//
//  AboutPageViewController.swift
//  SpendManagementApp
//
//  Created by Zi You Lim on 03/11/2025.
//

import UIKit

class AboutPageViewController: UIViewController {

    @IBOutlet weak var textView: UITextView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        textView.text = makeAbout()
    }
    
    func makeAbout() -> String {
        let title = "About This App\n"
        let introduction =
        """
        This page provides technologies, references and AI declaration for all external content used in the app.
        
        """
        
        let technologyTitle = "\nTechnologies Used\n"
        let technologies =
        """
        - Persistent Storage: Core Data & UserDefaults
        - Web Service: ExchangeRate-API (latest base-currency rates)
        - Maps and Location Services: MapKit
        - Swift Charts: SwiftUI Charts
        - Local Notifications: UNUserNotificationCenter
        
        """
        
        let referencesTitle = "\nReferences\n"
        let references =
        """
        Apple Developer Documentation
            - UIKit (https://developer.apple.com/documentation/uikit)
            - Foundation (https://developer.apple.com/documentation/foundation)
            - Contacts (https://developer.apple.com/documentation/Contacts)
                - Used for getting specific location address
            - SwiftUI (https://developer.apple.com/swiftui/)
                - Used for check box
                - Used for Swift Charts
            - UserNotifications (https://developer.apple.com/documentation/usernotifications)
                - Used for budget notification (when user close to maximum amount of budget)
            - MapKit (https://developer.apple.com/documentation/mapkit/)
                - Used for display map and let user select location
            - Charts (https://developer.apple.com/documentation/charts)
                - Used for Summaries page
        
        SF Symbols — Apple
        
        ExchangeRate-API (https://app.exchangerate-api.com/)
        
        Youtube Tutorial
            - Checkboxes in SwiftUI List (https://www.youtube.com/watch?v=MxuenEwKp28)
                - To build category check box in budget creation
            - SwiftUI Tutorial: Progress Bar with Animation (https://www.youtube.com/watch?v=jyOnBUxglcA)
                - To build progress bar to display on Budget page
            - Scrolling Charts in iOS 17 (https://www.youtube.com/watch?v=9nQh5QofS8c)
                - To build a chart that scrollable in Summaries > Overview
        
        """
        
        let aiDeclarationTitle = "\nAI Usage Declaration\n"
        let aiDeclaration =
        """
        AI tool(s) used: ChatGPT (https://chatgpt.com/)
        Usage was restricted to explaining Swift/UIKit concepts. All functional code was reviewed, tested, and adapted by the developer. No autogenerated code was submitted without verification.

        Prompts:
        - “In swift, how to make a something with live change when a user modify a text field"
        - “In swift, how to validate a string with 2 decimal places”
        - “In swift, how to get a country name using the country code”
        - "In swift, how to get all days in a specific month"
        - "In swift, how to get the full address of a place using its location"
        - "In swift, how to create a Done button within custom keyboard so that user can press it to dismiss the keyboard"
        - "In swiftui, using charts, how to display entire month from first day until last day in a chart"
        - "In swift, how to get a country currency by using country code"
        - "Generate a picture for me so that I can put in my app, my app name Spend Management App"

        Swift file(s) that used AI:
        - BudgetDetailViewController.swift (line 53 / 275)
        - CurrentBalanceViewController.swift (line 83)
        - Extension.swift (line 51)
        - CurrenciesTableViewController.swift (line 189 / 221)
        - CoreDataController.swift (line 678)
        - LocationSelectionViewController.swift (line 131 / 165)
        - RecordDetailViewController.swift (line 109 / 334)
        - RecordsViewController.swift (line 181)
        - OverviewChart.swift (line 39)
        - SummariesViewController.swift (line 134)
        - Assets.xcassets (AppIcon)
        
        """
        
        let reminderTitle = "\nReminder: How I Reference In Code\n"
        let reminder =
        """
        Above the code, I put a line that acknowledging the use of AI
        Template: I acknowledge the use of ChatGPT (https://chatgpt.com/) to [...]. The output (here) was [...].
        
        """
        
        var output = ""
        output.append(title)
        output.append(introduction)
        
        output.append(technologyTitle)
        output.append(technologies)
        
        output.append(referencesTitle)
        output.append(references)
        
        output.append(aiDeclarationTitle)
        output.append(aiDeclaration)
        
        output.append(reminderTitle)
        output.append(reminder)
        return output
    }
}
